language: node_js
sudo: required
node_js:
 - 10.19.0
cache: 
  yarn: true
  directories:
    - node_modules
    - $HOME/client/node_modules
    - $HOME/server/node_modules

install:
  - yarn install:deps
script:
  # - cd client && yarn test && cd ..
  - cd server && yarn lint && cd ..
after_success:
  - yarn build
  - echo "Build Successfull!"
