version: "3"

services:
  server1:
    depends_on: 
      - "db"
    build:
      context: ./server
    volumes:
      - "./server/src/:/usr/app/server/src/"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todolist
      PORT: 8000
  server2:
    depends_on: 
      - "db"
    build:
      context: ./server
    volumes:
      - "./server/src/:/usr/app/server/src/"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todolist
      PORT: 6000

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - "loadbalancer"
    environment:
      REACT_APP_SERVER_URL: http://localhost:5000/api

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todolist"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./server/migrations/:/docker-entrypoint-initdb.d/

  loadbalancer:
    image: nginx
    restart: always
    depends_on: 
      - "server1"
      - "server2"
    ports: 
      - "5000:5000"
    container_name: load_balancer
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf

volumes: 
  db-data: